import Head from "next/head";
import Image from "next/image";
import { Hero } from "../components/Home/Hero";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Night Login</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="">
        <Hero />
      </main>

      <footer className="">
        <a></a>
      </footer>
    </div>
  );
}
