import Head from "next/head";
import Image from "next/image";
import { AboutUs } from "../components/Home/AboutUs/AboutUs";
import { Communities } from "../components/Home/Communities/Communities";
import { Events } from "../components/Home/Events.tsx/Events";
import { Footer } from "../components/Home/Footer/Footer";
import { Hero } from "../components/Home/Hero/Hero";
import { Navbar } from "../components/Navbar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Night Login</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <Navbar />
        <Hero />
        <AboutUs />
        <Events />
        <Communities />
      </main>

      <footer className="">
        <Footer />
      </footer>
    </div>
  );
}
